# Generated by Django 2.2.6 on 2020-03-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('descripcionCategoria', models.CharField(max_length=10)),
            ],
        ),
    ]
