# Generated by Django 2.2.6 on 2020-03-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0002_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombreProveedor', models.CharField(max_length=15)),
                ('correoProveedor', models.CharField(max_length=30)),
                ('direccionProveedor', models.CharField(max_length=100)),
                ('telefonoProveedor', models.IntegerField(max_length=8)),
            ],
        ),
    ]
