# Generated by Django 2.2.6 on 2020-03-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0003_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefonoProveedor',
            field=models.IntegerField(),
        ),
    ]
