# Generated by Django 2.2.6 on 2020-03-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0004_auto_20200302_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('idGarantia', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('descripcionGarantia', models.CharField(max_length=100)),
                ('tiempoGarantiaMes', models.IntegerField()),
            ],
        ),
    ]
