# Generated by Django 2.2.6 on 2020-03-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0008_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('idFacturaDetalle', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
