# Generated by Django 2.2.6 on 2020-03-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0009_facturadetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturadetalle',
            name='idProducto',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.PROTECT, to='gestionadmin.Producto'),
            preserve_default=False,
        ),
    ]
