# Generated by Django 2.2.6 on 2020-03-15 18:53

from django.db import migrations, models
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0015_auto_20200315_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccionCliente',
            field=models.TextField(max_length=100, validators=[proyectoferreteria.apps.gestionadmin.models.validardireccion]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombreCliente',
            field=models.CharField(max_length=30, validators=[proyectoferreteria.apps.gestionadmin.models.validarnombre]),
        ),
    ]
