# Generated by Django 2.2.6 on 2020-03-15 19:35

from django.db import migrations, models
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0016_auto_20200315_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcionCategoria',
            field=models.CharField(max_length=30, validators=[proyectoferreteria.apps.gestionadmin.models.validarnombre]),
        ),
    ]
