# Generated by Django 2.2.6 on 2020-03-15 19:40

from django.db import migrations, models
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0017_auto_20200315_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='direccionEmpleado',
            field=models.TextField(max_length=100, validators=[proyectoferreteria.apps.gestionadmin.models.validardireccion]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombreEmpleado',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefonoEmpleado',
            field=models.CharField(max_length=8, validators=[proyectoferreteria.apps.gestionadmin.models.validarnumero]),
        ),
    ]
