# Generated by Django 2.2.6 on 2020-03-15 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0018_auto_20200315_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnoempleado',
            name='horaEntrada',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='turnoempleado',
            name='horaSalida',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
