# Generated by Django 2.2.6 on 2020-03-15 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0019_auto_20200315_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='idTurno',
        ),
        migrations.DeleteModel(
            name='TurnoEmpleado',
        ),
    ]
