# Generated by Django 2.2.6 on 2020-03-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0024_auto_20200315_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnoempleado',
            name='horaEntrada',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='turnoempleado',
            name='horaSalida',
            field=models.TimeField(),
        ),
    ]
