# Generated by Django 2.2.6 on 2020-03-15 23:43

from django.db import migrations, models
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0027_auto_20200315_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnoempleado',
            name='horaEntrada',
            field=models.CharField(max_length=5, validators=[proyectoferreteria.apps.gestionadmin.models.validarhora]),
        ),
        migrations.AlterField(
            model_name='turnoempleado',
            name='horaSalida',
            field=models.CharField(max_length=5, validators=[proyectoferreteria.apps.gestionadmin.models.validarhora]),
        ),
    ]
