# Generated by Django 2.2.6 on 2020-03-16 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0029_auto_20200315_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planilla',
            name='antiguedad',
        ),
    ]
