# Generated by Django 2.2.6 on 2020-03-16 01:14

from django.db import migrations, models
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0033_auto_20200315_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nombreMarca',
            field=models.CharField(max_length=30, validators=[proyectoferreteria.apps.gestionadmin.models.validarnombre]),
        ),
    ]
