# Generated by Django 2.2.6 on 2020-03-16 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0034_auto_20200315_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='existencia',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='existenciaMinima',
        ),
    ]
