# Generated by Django 2.2.6 on 2020-03-16 01:56

from django.db import migrations, models
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0037_auto_20200315_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioCompra',
            field=models.DecimalField(decimal_places=3, max_digits=8, validators=[proyectoferreteria.apps.gestionadmin.models.validarquenoseacero]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioVenta',
            field=models.DecimalField(decimal_places=3, max_digits=8, validators=[proyectoferreteria.apps.gestionadmin.models.validarquenoseacero]),
        ),
    ]
