# Generated by Django 2.2.6 on 2020-03-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0040_producto_existenciaminima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioCompra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioVenta',
            field=models.IntegerField(),
        ),
    ]
