# Generated by Django 2.2.6 on 2020-03-16 02:42

from django.db import migrations, models
import django.db.models.deletion
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0041_auto_20200315_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='idGarantia',
            field=models.ForeignKey(default=5667, on_delete=django.db.models.deletion.PROTECT, to='gestionadmin.Garantia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formapago',
            name='descripcionFormaPago',
            field=models.TextField(max_length=30, validators=[proyectoferreteria.apps.gestionadmin.models.validarnombre]),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='descripcionMetodoPago',
            field=models.TextField(max_length=30, validators=[proyectoferreteria.apps.gestionadmin.models.validarnombre]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='existencia',
            field=models.IntegerField(validators=[proyectoferreteria.apps.gestionadmin.models.validarquenoseacero]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='existenciaMinima',
            field=models.IntegerField(validators=[proyectoferreteria.apps.gestionadmin.models.validar_mayor_a_tres]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioCompra',
            field=models.IntegerField(validators=[proyectoferreteria.apps.gestionadmin.models.validarquenoseacero]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioVenta',
            field=models.IntegerField(validators=[proyectoferreteria.apps.gestionadmin.models.validarquenoseacero]),
        ),
    ]
