# Generated by Django 2.2.6 on 2020-03-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0044_auto_20200315_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturadetalle',
            name='idProducto',
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='idProducto',
            field=models.ManyToManyField(to='gestionadmin.Producto'),
        ),
    ]
