# Generated by Django 2.2.6 on 2020-03-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0045_auto_20200315_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturadetalle',
            name='idProducto',
        ),
    ]
