# Generated by Django 2.2.6 on 2020-03-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0047_facturadetalle_idproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturadetalle',
            name='idFacturaEncabezado',
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='idFacturaEncabezado',
            field=models.ManyToManyField(to='gestionadmin.FacturaEncabezado'),
        ),
    ]
