# Generated by Django 2.2.6 on 2020-03-16 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0048_auto_20200315_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturadetalle',
            name='idFacturaEncabezado',
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='FacturaEncabezado_id',
            field=models.OneToOneField(default=4567, on_delete=django.db.models.deletion.PROTECT, to='gestionadmin.FacturaEncabezado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facturaencabezado',
            name='idFacturaEncabezado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
