# Generated by Django 2.2.6 on 2020-03-16 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0049_auto_20200315_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturadetalle',
            old_name='FacturaEncabezado_id',
            new_name='idFacturaEncabezado',
        ),
        migrations.RemoveField(
            model_name='facturadetalle',
            name='idProducto',
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='idProducto',
            field=models.ForeignKey(default=456, on_delete=django.db.models.deletion.PROTECT, to='gestionadmin.Producto'),
            preserve_default=False,
        ),
    ]
