# Generated by Django 2.2.6 on 2020-03-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0050_auto_20200315_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='idMarca',
            field=models.IntegerField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
