# Generated by Django 2.2.6 on 2020-03-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0051_auto_20200316_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='idMarca',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
