# Generated by Django 2.2.6 on 2020-03-18 03:46

from django.db import migrations, models
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0055_auto_20200317_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='idCategoria',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[proyectoferreteria.apps.gestionadmin.models.validartamaño]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idCliente',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[proyectoferreteria.apps.gestionadmin.models.validartamaño]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='idEmpleado',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[proyectoferreteria.apps.gestionadmin.models.validartamaño]),
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='idFacturaDetalle',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[proyectoferreteria.apps.gestionadmin.models.validartamaño]),
        ),
        migrations.AlterField(
            model_name='facturaencabezado',
            name='idFacturaEncabezado',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[proyectoferreteria.apps.gestionadmin.models.validartamaño]),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='idFormaPago',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[proyectoferreteria.apps.gestionadmin.models.validartamaño]),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='idGarantia',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[proyectoferreteria.apps.gestionadmin.models.validartamaño]),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='idMetodoPago',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[proyectoferreteria.apps.gestionadmin.models.validartamaño]),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='idPlanilla',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[proyectoferreteria.apps.gestionadmin.models.validartamaño]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[proyectoferreteria.apps.gestionadmin.models.validartamaño]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='idProveedor',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[proyectoferreteria.apps.gestionadmin.models.validartamaño]),
        ),
        migrations.AlterField(
            model_name='turnoempleado',
            name='idTurno',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[proyectoferreteria.apps.gestionadmin.models.validartamaño]),
        ),
    ]
