# Generated by Django 2.2.6 on 2020-03-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0056_auto_20200317_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaencabezado',
            name='isv15',
        ),
        migrations.RemoveField(
            model_name='facturaencabezado',
            name='isv18',
        ),
        migrations.RemoveField(
            model_name='facturaencabezado',
            name='totalFactura',
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='isv15',
            field=models.IntegerField(default=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='isv18',
            field=models.IntegerField(default=5678),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='totalFactura',
            field=models.IntegerField(default=788),
            preserve_default=False,
        ),
    ]
