# Generated by Django 2.2.6 on 2020-03-20 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0057_auto_20200319_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaencabezado',
            name='idCliente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='gestionadmin.Cliente'),
        ),
        migrations.AlterField(
            model_name='facturaencabezado',
            name='idFacturaEncabezado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
