# Generated by Django 2.2.6 on 2020-03-20 01:20

from django.db import migrations, models
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0058_auto_20200319_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturadetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[proyectoferreteria.apps.gestionadmin.models.validarquenoseacero]),
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='isv15',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='isv18',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
