# Generated by Django 2.2.6 on 2020-03-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0059_auto_20200319_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturadetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
