# Generated by Django 2.2.6 on 2020-03-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0060_auto_20200319_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturadetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='isv15',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='isv18',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
