# Generated by Django 2.2.6 on 2020-03-20 01:29

from django.db import migrations, models
import django.db.models.deletion
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0061_auto_20200319_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturadetalle',
            name='isv15',
        ),
        migrations.RemoveField(
            model_name='facturadetalle',
            name='isv18',
        ),
        migrations.RemoveField(
            model_name='facturadetalle',
            name='totalFactura',
        ),
        migrations.AddField(
            model_name='facturaencabezado',
            name='isv15',
            field=models.IntegerField(default=233),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturaencabezado',
            name='isv18',
            field=models.IntegerField(default=677),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturaencabezado',
            name='totalFactura',
            field=models.IntegerField(default=667),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='cantidad',
            field=models.IntegerField(validators=[proyectoferreteria.apps.gestionadmin.models.validarquenoseacero]),
        ),
        migrations.AlterField(
            model_name='facturaencabezado',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionadmin.Cliente'),
        ),
        migrations.AlterField(
            model_name='facturaencabezado',
            name='idFacturaEncabezado',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[proyectoferreteria.apps.gestionadmin.models.validartamaño]),
        ),
    ]
