# Generated by Django 3.0.4 on 2020-03-26 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0062_auto_20200319_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='descripcionCategoria',
            new_name='Descripcion_Categoria',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='idCategoria',
            new_name='Id_Categoria',
        ),
    ]
