# Generated by Django 3.0.4 on 2020-03-26 00:34

from django.db import migrations, models
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0063_auto_20200325_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='Id_Categoria',
            field=models.AutoField(primary_key=True, serialize=False, validators=[proyectoferreteria.apps.gestionadmin.models.validartamaño]),
        ),
    ]
