# Generated by Django 3.0.4 on 2020-03-26 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0065_auto_20200325_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='IdProveedor',
            new_name='idProveedor',
        ),
    ]
