# Generated by Django 3.0.4 on 2020-03-26 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0067_auto_20200325_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='correoProveedor',
            new_name='Correo_Proveedor',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='direccionProveedor',
            new_name='Direccion_Proveedor',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='idProveedor',
            new_name='Id_Proveedor',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombreProveedor',
            new_name='Nombre_Proveedor',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='telefonoProveedor',
            new_name='Telefono_Proveedor',
        ),
    ]
