# Generated by Django 3.0.4 on 2020-03-26 01:09

from django.db import migrations, models
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0068_auto_20200325_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='Id_Proveedor',
            field=models.AutoField(primary_key=True, serialize=False, validators=[proyectoferreteria.apps.gestionadmin.models.validartamaño]),
        ),
    ]
