# Generated by Django 3.0.4 on 2020-03-26 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0069_auto_20200325_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formapago',
            old_name='descripcionFormaPago',
            new_name='Descripcion_FormaPago',
        ),
        migrations.RenameField(
            model_name='formapago',
            old_name='idFormaPago',
            new_name='Id_FormaPago',
        ),
    ]
