# Generated by Django 3.0.4 on 2020-03-26 01:13

from django.db import migrations, models
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0071_auto_20200325_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapago',
            name='Id_FormaPago',
            field=models.AutoField(primary_key=True, serialize=False, validators=[proyectoferreteria.apps.gestionadmin.models.validartamaño]),
        ),
    ]
