# Generated by Django 3.0.4 on 2020-03-26 01:23

from django.db import migrations, models
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0072_auto_20200325_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='IHSS',
            field=models.IntegerField(validators=[proyectoferreteria.apps.gestionadmin.models.validarnegativos]),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='RAP',
            field=models.IntegerField(validators=[proyectoferreteria.apps.gestionadmin.models.validarnegativos]),
        ),
    ]
