# Generated by Django 3.0.4 on 2020-03-26 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0073_auto_20200325_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metodopago',
            old_name='descripcionMetodoPago',
            new_name='Descripcion_MetodoPago',
        ),
        migrations.RenameField(
            model_name='metodopago',
            old_name='idMetodoPago',
            new_name='Id_Metodo_Pago',
        ),
    ]
