# Generated by Django 3.0.4 on 2020-03-26 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0078_auto_20200325_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planilla',
            old_name='idPlanilla',
            new_name='Id_Planilla',
        ),
        migrations.RenameField(
            model_name='planilla',
            old_name='sueldoBase',
            new_name='Sueldo_Base',
        ),
    ]
