# Generated by Django 3.0.4 on 2020-03-26 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0080_auto_20200325_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='direccionEmpleado',
            new_name='Direccion_Empleado',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='idEmpleado',
            new_name='Id_Empleado',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='idPlanilla',
            new_name='Id_Planilla',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='idTurno',
            new_name='Id_Turno',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='nombreEmpleado',
            new_name='Nombre_Empleado',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='telefonoEmpleado',
            new_name='Telefono_Empleado',
        ),
    ]
