# Generated by Django 3.0.4 on 2020-03-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0084_auto_20200326_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturaencabezado',
            old_name='codigoCAI',
            new_name='Codigo_CAI',
        ),
        migrations.RenameField(
            model_name='facturaencabezado',
            old_name='isv15',
            new_name='ISV15',
        ),
        migrations.RenameField(
            model_name='facturaencabezado',
            old_name='isv18',
            new_name='ISV18',
        ),
        migrations.RenameField(
            model_name='facturaencabezado',
            old_name='idCliente',
            new_name='Id_Cliente',
        ),
        migrations.RenameField(
            model_name='facturaencabezado',
            old_name='idEmpleado',
            new_name='Id_Empleado',
        ),
        migrations.RenameField(
            model_name='facturaencabezado',
            old_name='idFacturaEncabezado',
            new_name='Id_Factura_Encabezado',
        ),
        migrations.RenameField(
            model_name='facturaencabezado',
            old_name='idFormaPago',
            new_name='Id_FormaPago',
        ),
        migrations.RenameField(
            model_name='facturaencabezado',
            old_name='idMetodoPago',
            new_name='Id_MetodoPago',
        ),
        migrations.RenameField(
            model_name='facturaencabezado',
            old_name='nSar',
            new_name='NSar',
        ),
        migrations.RenameField(
            model_name='facturaencabezado',
            old_name='fecha',
            new_name='Necha',
        ),
        migrations.RenameField(
            model_name='facturaencabezado',
            old_name='totalFactura',
            new_name='Total_Factura',
        ),
    ]
