# Generated by Django 3.0.4 on 2020-03-26 19:48

from django.db import migrations, models
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0085_auto_20200326_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaencabezado',
            name='Id_Factura_Encabezado',
            field=models.AutoField(primary_key=True, serialize=False, validators=[proyectoferreteria.apps.gestionadmin.models.validartamaño]),
        ),
    ]
