# Generated by Django 3.0.4 on 2020-03-26 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0086_auto_20200326_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturaencabezado',
            old_name='NSar',
            new_name='Numero_Sar',
        ),
    ]
