# Generated by Django 3.0.4 on 2020-03-26 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0089_auto_20200326_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metodopago',
            old_name='Descripcion_MetodoPago',
            new_name='Descripcion_Metodo_Pago',
        ),
    ]
