# Generated by Django 3.0.4 on 2020-03-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0090_auto_20200326_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formapago',
            old_name='Descripcion_FormaPago',
            new_name='descripcionFormaPago',
        ),
        migrations.RenameField(
            model_name='formapago',
            old_name='Id_FormaPago',
            new_name='idFormaPago',
        ),
    ]
