# Generated by Django 3.0.4 on 2020-03-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0091_auto_20200326_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formapago',
            old_name='descripcionFormaPago',
            new_name='Descripcion_Forma_Pago',
        ),
        migrations.RenameField(
            model_name='formapago',
            old_name='idFormaPago',
            new_name='Id_Forma_Pago',
        ),
        migrations.RenameField(
            model_name='metodopago',
            old_name='Descripcion_Metodo_Pago',
            new_name='descripcionMetodoPago',
        ),
        migrations.RenameField(
            model_name='metodopago',
            old_name='Id_Metodo_Pago',
            new_name='idMetodoPago',
        ),
    ]
