# Generated by Django 3.0.4 on 2020-03-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0092_auto_20200326_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturadetalle',
            old_name='Id_FacturaDetalle',
            new_name='Id_Factura_Detalle',
        ),
    ]
