# Generated by Django 2.2.6 on 2020-04-03 00:19

from django.db import migrations, models
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0096_auto_20200402_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='idMarca',
            field=models.AutoField(primary_key=True, serialize=False, validators=[proyectoferreteria.apps.gestionadmin.models.validartamaño]),
        ),
    ]
