# Generated by Django 2.2.6 on 2020-04-03 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0097_auto_20200402_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
