# Generated by Django 2.2.6 on 2020-04-03 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0098_auto_20200402_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
    ]
