# Generated by Django 2.2.6 on 2020-04-09 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0100_auto_20200408_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacturaEncabezado',
            new_name='Factura',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='Id_Factura_Encabezado',
            new_name='Id_Factura',
        ),
        migrations.DeleteModel(
            name='FacturaDetalle',
        ),
    ]
