# Generated by Django 2.2.6 on 2020-04-09 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0101_auto_20200408_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='Id_Cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestionadmin.Cliente'),
        ),
    ]
