# Generated by Django 2.2.6 on 2020-04-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0102_auto_20200408_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='Fecha',
            field=models.DateTimeField(),
        ),
    ]
