# Generated by Django 2.2.6 on 2020-04-09 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0103_auto_20200408_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='Fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Id_Cliente',
            field=models.ForeignKey(default=12233, on_delete=django.db.models.deletion.PROTECT, to='gestionadmin.Cliente'),
            preserve_default=False,
        ),
    ]
