# Generated by Django 2.2.6 on 2020-04-09 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0105_auto_20200409_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='Id_Cliente',
            field=models.ForeignKey(default=324, on_delete=django.db.models.deletion.PROTECT, to='gestionadmin.Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='Id_Empleado',
            field=models.ForeignKey(default=23434, on_delete=django.db.models.deletion.PROTECT, to='gestionadmin.Empleado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='Id_FormaPago',
            field=models.ForeignKey(default=23434, on_delete=django.db.models.deletion.PROTECT, to='gestionadmin.FormaPago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='Id_MetodoPago',
            field=models.ForeignKey(default=343545, on_delete=django.db.models.deletion.PROTECT, to='gestionadmin.MetodoPago'),
            preserve_default=False,
        ),
    ]
