# Generated by Django 2.2.6 on 2020-04-09 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0107_auto_20200409_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='Fecha',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 4, 9, 13, 33, 23, 902972)),
        ),
    ]
