# Generated by Django 3.0.4 on 2020-04-17 10:35

from django.db import migrations, models
import django.db.models.deletion
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0111_auto_20200413_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='Codigo_CAI',
            field=models.CharField(max_length=35, verbose_name='Codigo CAI'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='ISV15',
            field=models.IntegerField(validators=[proyectoferreteria.apps.gestionadmin.models.validarnegativos], verbose_name='ISV 15%'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='ISV18',
            field=models.IntegerField(validators=[proyectoferreteria.apps.gestionadmin.models.validarnegativos], verbose_name='ISV 18%'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Id_Cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestionadmin.Cliente', verbose_name='Id de cliente'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Id_Empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionadmin.Empleado', verbose_name='Id de empleado'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Id_Factura',
            field=models.AutoField(primary_key=True, serialize=False, validators=[proyectoferreteria.apps.gestionadmin.models.validartamaño], verbose_name='Id de factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Id_FormaPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionadmin.FormaPago', verbose_name='Id de la forma de oago'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Id_MetodoPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionadmin.MetodoPago', verbose_name='Id del metodo de pago'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Id_producto',
            field=models.ManyToManyField(to='gestionadmin.Producto', verbose_name='Id del producto'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Numero_Sar',
            field=models.CharField(max_length=15, verbose_name='Numero de la SAR'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Total_Factura',
            field=models.IntegerField(verbose_name='Total de la factura'),
        ),
    ]
