# Generated by Django 3.0.5 on 2020-04-23 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0114_auto_20200417_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='Id_FormaPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionadmin.FormaPago', verbose_name='Forma de Pago'),
        ),
    ]
