# Generated by Django 2.2.6 on 2020-04-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0116_auto_20200424_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Correo_Cliente',
            field=models.EmailField(blank=True, max_length=30, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='Correo_Proveedor',
            field=models.EmailField(blank=True, max_length=30, verbose_name='Correo'),
        ),
    ]
