# Generated by Django 2.2.6 on 2020-04-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0117_auto_20200424_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantia',
            name='Descripcion_Garantia',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='Tiempo_Garantia_Mes',
            field=models.IntegerField(verbose_name='Tiempo garantia'),
        ),
    ]
