# Generated by Django 2.2.6 on 2020-04-25 19:41

from django.db import migrations, models
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0119_auto_20200425_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Correo_Cliente',
            field=models.EmailField(blank=True, max_length=30, null=True, validators=[proyectoferreteria.apps.gestionadmin.models.validarcorreoexistenteCliente], verbose_name='Correo'),
        ),
    ]
