# Generated by Django 2.2.6 on 2020-06-15 11:36

from django.db import migrations, models
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0120_auto_20200425_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='Descripcion_Categoria',
            field=models.CharField(max_length=30, unique=True, validators=[proyectoferreteria.apps.gestionadmin.models.validarnombre], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Correo_Cliente',
            field=models.EmailField(blank=True, max_length=30, null=True, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Codigo_CAI',
            field=models.CharField(default='114-560-345KJ', max_length=36, verbose_name='Código CAI'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Numero_Sar',
            field=models.CharField(default='004-340-34523', max_length=15, validators=[proyectoferreteria.apps.gestionadmin.models.validarCAIySAR, proyectoferreteria.apps.gestionadmin.models.validarsar], verbose_name='Número de la SAR'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Total_Factura',
            field=models.FloatField(validators=[proyectoferreteria.apps.gestionadmin.models.validarnegativos], verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='Descripcion_Forma_Pago',
            field=models.TextField(max_length=30, unique=True, validators=[proyectoferreteria.apps.gestionadmin.models.validarnombre], verbose_name='  Descripcion'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='Descripcion_Garantia',
            field=models.TextField(max_length=50, unique=True, validators=[proyectoferreteria.apps.gestionadmin.models.validarnombre], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='Tiempo_Garantia_Mes',
            field=models.IntegerField(validators=[proyectoferreteria.apps.gestionadmin.models.validartiempogarantia], verbose_name='Tiempo garantía por mes'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombreMarca',
            field=models.CharField(max_length=30, unique=True, validators=[proyectoferreteria.apps.gestionadmin.models.validarnombre], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='descripcionMetodoPago',
            field=models.TextField(max_length=30, unique=True, validators=[proyectoferreteria.apps.gestionadmin.models.validarnombre], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='Sueldo_Base',
            field=models.IntegerField(unique=True, validators=[proyectoferreteria.apps.gestionadmin.models.validarsueldo], verbose_name='Sueldo Base'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Nombre_Producto',
            field=models.CharField(max_length=40, unique=True, validators=[proyectoferreteria.apps.gestionadmin.models.validarnombre], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='Correo_Proveedor',
            field=models.EmailField(blank=True, max_length=30, null=True, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='Nombre_Proveedor',
            field=models.CharField(max_length=35, unique=True, validators=[proyectoferreteria.apps.gestionadmin.models.validarnombre], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='turnoempleado',
            name='Turno',
            field=models.CharField(max_length=30, unique=True, validators=[proyectoferreteria.apps.gestionadmin.models.validarnombre], verbose_name='Turno'),
        ),
    ]
