# Generated by Django 2.2.6 on 2020-06-15 12:26

from django.db import migrations, models
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0121_auto_20200615_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='IHSS',
            field=models.FloatField(validators=[proyectoferreteria.apps.gestionadmin.models.validarnegativos], verbose_name='IHSS'),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='RAP',
            field=models.FloatField(validators=[proyectoferreteria.apps.gestionadmin.models.validarnegativos], verbose_name='RAP'),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='Sueldo_Base',
            field=models.FloatField(unique=True, validators=[proyectoferreteria.apps.gestionadmin.models.validarsueldo], verbose_name='Sueldo Base'),
        ),
    ]
