# Generated by Django 2.2.6 on 2020-06-15 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0122_auto_20200615_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='Id_Empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Empleado'),
        ),
    ]
