# Generated by Django 2.2.6 on 2020-06-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0123_auto_20200615_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
    ]
