# Generated by Django 2.2.6 on 2020-06-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0125_comprasdet_comprasenc'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasenc',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
