# Generated by Django 2.2.6 on 2020-06-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0126_comprasenc_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
