# Generated by Django 2.2.6 on 2020-06-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0127_producto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasenc',
            name='fecha_factura',
            field=models.DateField(blank=True, null=True),
        ),
    ]
