# Generated by Django 2.2.6 on 2020-06-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0128_auto_20200617_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprasenc',
            name='fecha_compra',
        ),
    ]
