# Generated by Django 2.2.6 on 2020-06-18 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0129_remove_comprasenc_fecha_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprasenc',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='comprasenc',
            name='cliente',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, to='gestionadmin.Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comprasdet',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionadmin.ComprasEnc'),
        ),
        migrations.AlterField(
            model_name='comprasdet',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionadmin.Producto'),
        ),
    ]
