# Generated by Django 2.2.6 on 2020-06-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0130_auto_20200618_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprasenc',
            name='observacion',
        ),
    ]
