# Generated by Django 2.2.6 on 2020-06-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0131_remove_comprasenc_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasenc',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
