# Generated by Django 2.2.6 on 2020-06-18 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0132_comprasenc_observacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprasenc',
            name='observacion',
        ),
        migrations.AddField(
            model_name='comprasenc',
            name='empleado',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='gestionadmin.Empleado'),
            preserve_default=False,
        ),
    ]
