# Generated by Django 2.2.6 on 2020-06-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0133_auto_20200618_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprasenc',
            name='empleado',
        ),
    ]
