# Generated by Django 2.2.6 on 2020-06-24 20:01

from django.db import migrations, models
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0137_auto_20200624_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Telefono_Cliente',
            field=models.CharField(max_length=8, unique=True, validators=[proyectoferreteria.apps.gestionadmin.models.validarnumero], verbose_name='Teléfono'),
        ),
    ]
