# Generated by Django 2.2.6 on 2020-06-24 21:35

from django.db import migrations, models
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0139_cliente_identidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Identidad',
            field=models.CharField(max_length=13, unique=True, validators=[proyectoferreteria.apps.gestionadmin.models.validaridentidad], verbose_name='Identidad'),
        ),
    ]
