# Generated by Django 2.2.6 on 2020-06-24 22:15

from django.db import migrations, models
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0140_auto_20200624_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='IHSS',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[proyectoferreteria.apps.gestionadmin.models.validarnegativos], verbose_name='IHSS'),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='RAP',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[proyectoferreteria.apps.gestionadmin.models.validarnegativos], verbose_name='RAP'),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='Sueldo_Base',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[proyectoferreteria.apps.gestionadmin.models.validarnegativos], verbose_name='Sueldo Base'),
        ),
    ]
