# Generated by Django 2.2.6 on 2020-06-27 16:29

from django.db import migrations, models
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0141_auto_20200624_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasenc',
            name='fecha_factura',
            field=models.DateField(blank=True, default='2020-06-27', null=True),
        ),
        migrations.AlterField(
            model_name='turnoempleado',
            name='Hora_de_Entrada',
            field=models.CharField(default='17:40', max_length=5, validators=[proyectoferreteria.apps.gestionadmin.models.validarhora], verbose_name='Hora entrada'),
        ),
        migrations.AlterField(
            model_name='turnoempleado',
            name='Hora_de_Salida',
            field=models.CharField(default='23:40', max_length=5, validators=[proyectoferreteria.apps.gestionadmin.models.validarhora], verbose_name='Hora salida'),
        ),
        migrations.AlterField(
            model_name='turnoempleado',
            name='Turno',
            field=models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino')], max_length=30, unique=True, validators=[proyectoferreteria.apps.gestionadmin.models.validarnombre], verbose_name='Turno'),
        ),
    ]
