# Generated by Django 2.2.6 on 2020-06-28 09:21

from django.db import migrations, models
import proyectoferreteria.apps.gestionadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0142_auto_20200627_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasenc',
            name='fecha_factura',
            field=models.DateField(blank=True, default='2020-06-28', null=True),
        ),
        migrations.AlterField(
            model_name='turnoempleado',
            name='Turno',
            field=models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Nocturno', 'Nocturno'), ('Mixto', 'Mixto'), ('Especial', 'Especial')], default='Matutino', max_length=30, unique=True, validators=[proyectoferreteria.apps.gestionadmin.models.validarnombre], verbose_name='Turno'),
        ),
    ]
