# Generated by Django 2.2.6 on 2020-07-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionadmin', '0143_auto_20200628_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasenc',
            name='fecha_factura',
            field=models.DateField(blank=True, default='2020-07-18', null=True),
        ),
        migrations.AlterField(
            model_name='comprasenc',
            name='no_factura',
            field=models.CharField(default='056-052-68753', max_length=100),
        ),
    ]
